# This Jupyter Notebook covers all the required topics:

1) Python Basics including loops, functions, list and dictionaries

3) NumPy arrays and vectorized operations

4) Matrix multiplication and broadcasting

# Python Basics

In [1]:
print("Hello I am Muhammad Hassan , 2023-bs-ai-176 ")

x = 67  
y = 76
name = "Hassan"  

sum = x + 5
product = x * y
division = x / 2
reminder = x % 3

print(f"Sum: {sum}, Product: {product}, Division: {division}, Modulus/Reminder: {reminder}")

Hello I am Muhammad Hassan , 2023-bs-ai-176 
Sum: 72, Product: 5092, Division: 33.5, Modulus/Reminder: 1


# Loops

For Loop with range

In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


For loop with list

In [3]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(f"Fruit: {fruit}")

Fruit: apple
Fruit: banana
Fruit: cherry


While loop

In [5]:
counter = 0
while counter < 3:
    print("Counter: " ,counter)
    counter = counter + 1

Counter:  0
Counter:  1
Counter:  2


Nested loop

In [16]:
for i in range(3):
    for j in range(2):
        print(f"i={i}, j={j}")

i=0, j=0
i=0, j=1
i=1, j=0
i=1, j=1
i=2, j=0
i=2, j=1


For-else

While-else

In [7]:
num = 0
while num < 3:
    print(num)
    num += 1
else:
    print("loop done")

0
1
2
loop done


# Functions 

Simple function

In [8]:
def greet(name):
    return f"Hello, {name}"

print(greet("Hassan"))

Hello, Hassan


Function with default parameter

In [11]:
def power(base, exponent=3):
    return base ** exponent

print("Power(3):",power(3))
print("Power(8):",power(8))

Power(3): 27
Power(8): 512


*args for variable number of arguments

In [1]:
def sum_all(*numbers):
    return sum(numbers)

print(f"Sum: {sum_all(66, 67, 67, 67)}")


Sum: 267


**kwargs for keyword arguments

In [2]:
def person_info(**info):
    for key, value in info.items():
        print(f"{key}: {value}")

person_info(name="Hassan", age=21, city="Faisalabad")

name: Hassan
age: 21
city: Faisalabad


Recursive function

In [4]:
def factorial(n):
    if n == 0:
        return 1
    return n * factorial(n - 1)

print(f"Factorial of 5: {factorial(5)}")

Factorial of 5: 120


#  Lists

In [23]:

list = [1, 2, 3, 4, 5]
print(f" list: {list}")

list.append(6)
print(f"1. After append(6): {list}")

list.insert(4, 67)
print(f"2. After insert(4, 67): {list}")

list.sort()
print(f"3. After sorting: {list}")

list.remove(67)
print(f"4. After remove(67): {list}")

popped = list.pop(3)
print(f"5. After pop(3): {list}, Popped: {popped}")

list.reverse()
print("6. List after reverse : " , list)

print("7. index no: ", list.index(3))

data = list.clear()
print("8. After clearing : " , data)

 list: [1, 2, 3, 4, 5]
1. After append(6): [1, 2, 3, 4, 5, 6]
2. After insert(4, 67): [1, 2, 3, 4, 67, 5, 6]
3. After sorting: [1, 2, 3, 4, 5, 6, 67]
4. After remove(67): [1, 2, 3, 4, 5, 6]
5. After pop(3): [1, 2, 3, 5, 6], Popped: 4
6. List after reverse :  [6, 5, 3, 2, 1]
7. index no:  2
8. After clearing :  None


# Dictionaries

In [24]:
print(" BASICS OF DICTIONARY")
student = {
    "name": "Hassan",
    "age": 21,
    "major": "Artificial Intelligence",
    "grades": {"stats": 90, "Analysis of Algo": 85, "Assembly": 88}
}
print(f"Student dictionary: {student}")

 BASICS OF DICTIONARY
Student dictionary: {'name': 'Hassan', 'age': 21, 'major': 'Artificial Intelligence', 'grades': {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88}}


## LIST TO DICTIONARY

In [25]:

keys = ['a', 'b', 'c']
values = [1, 2, 3]

dict_from_list = dict(zip(keys, values))
print(f"Dictionary from zip: {dict_from_list}")


Dictionary from zip: {'a': 1, 'b': 2, 'c': 3}


## DICTIONARY TO LIST

In [2]:
student = {
    "name": "Hassan",
    "age": 21,
    "major": "Artificial Intelligence",
    "grades": {"stats": 90, "Analysis of Algo": 85, "Assembly": 88}
}

keys_list = list(student.keys())
print(f"Keys as list: {keys_list}")

values_list = list(student.values())
print(f"Values as list: {values_list}")

items_list = list(student.items())
print(f"Items as list of tuples: {items_list}")

Keys as list: ['name', 'age', 'major', 'grades']
Values as list: ['Hassan', 21, 'Artificial Intelligence', {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88}]
Items as list of tuples: [('name', 'Hassan'), ('age', 21), ('major', 'Artificial Intelligence'), ('grades', {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88})]


In [3]:
print("TUPLES WITH DICTIONARIES")

coordinate_dict = {
    (0, 0): "Origin",
    (1, 2): "Point A",
    (3, 4): "Point B"
}
print(f"Dictionary with tuple keys: {coordinate_dict}")
print(f"Value at (1, 2): {coordinate_dict[(1, 2)]}")

TUPLES WITH DICTIONARIES
Dictionary with tuple keys: {(0, 0): 'Origin', (1, 2): 'Point A', (3, 4): 'Point B'}
Value at (1, 2): Point A


## Dictionary

In [4]:
print("DICTIONARY METHODS")

print(f"get('name'): {student.get('name')}")
print(f"get('nonexistent', 'default'): {student.get('nonexistent', 'default')}")


student.update({"year": "Junior", "gpa": 3.8})
print(f"After update: {student}")


popped_item = student.pop("age")
print(f"After pop('age'): {student}, Popped: {popped_item}")

last_item = student.popitem()
print(f"After popitem(): {student}, Last item: {last_item}")

student.setdefault("status", "Active")
print(f"After setdefault: {student}")

DICTIONARY METHODS
get('name'): Hassan
get('nonexistent', 'default'): default
After update: {'name': 'Hassan', 'age': 21, 'major': 'Artificial Intelligence', 'grades': {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88}, 'year': 'Junior', 'gpa': 3.8}
After pop('age'): {'name': 'Hassan', 'major': 'Artificial Intelligence', 'grades': {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88}, 'year': 'Junior', 'gpa': 3.8}, Popped: 21
After popitem(): {'name': 'Hassan', 'major': 'Artificial Intelligence', 'grades': {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88}, 'year': 'Junior'}, Last item: ('gpa', 3.8)
After setdefault: {'name': 'Hassan', 'major': 'Artificial Intelligence', 'grades': {'stats': 90, 'Analysis of Algo': 85, 'Assembly': 88}, 'year': 'Junior', 'status': 'Active'}


# NumPy

In [7]:
import numpy as np

In [8]:
print("NUMPY ARRAYS")

arr1 = np.array([1, 2, 3, 4, 5])
print(f"1D Array: {arr1}")
print(f"Type: {type(arr1)}")
print(f"Shape: {arr1.shape}")
print(f"Data type: {arr1.dtype}")

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr2d}")
print(f"Shape: {arr2d.shape}")

NUMPY ARRAYS
1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Shape: (5,)
Data type: int32

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [71]:

zeros_arr = np.zeros((3, 3))
print(f"\nZeros array:\n{zeros_arr}")

ones_arr = np.ones((2, 4))
print(f"\nOnes array:\n{ones_arr}")

identity_arr = np.eye(3)
print(f"\nIdentity matrix:\n{identity_arr}")

range_arr = np.arange(0, 10, 2)
print(f"\nArray from arange: {range_arr}")

linspace_arr = np.linspace(0, 1, 5)
print(f"\nLinspace array: {linspace_arr}")


Zeros array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array from arange: [0 2 4 6 8]

Linspace array: [0.   0.25 0.5  0.75 1.  ]


## Vectorized Operations

In [25]:
print("VECTORIZED OPERATIONS")

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(f"Array a: {a}")
print(f"Array b: {b}")


print(f"\nElement-wise addition: {a + b}")
print(f"Element-wise subtraction: {a - b}")
print(f"Element-wise multiplication: {a * b}")
print(f"Element-wise division: {a / b}")
print(f"Element-wise exponent: {a ** 2}")
print(f"Element-wise square root: {np.sqrt(a)}")


print(f"\nElement-wise comparison (a > 2): {a > 2}")
print(f"Element-wise comparison (a == b): {a == b}")

print(f"\nSum of a: {np.sum(a)}")
print(f"Mean of a: {np.mean(a)}")
print(f"Standard deviation of a: {np.std(a)}")
print(f"Minimum of a: {np.min(a)}")
print(f"Maximum of a: {np.max(a)}")
print(f"Index of max value: {np.argmax(a)}")


VECTORIZED OPERATIONS
Array a: [1 2 3 4]
Array b: [5 6 7 8]

Element-wise addition: [ 6  8 10 12]
Element-wise subtraction: [-4 -4 -4 -4]
Element-wise multiplication: [ 5 12 21 32]
Element-wise division: [0.2        0.33333333 0.42857143 0.5       ]
Element-wise exponent: [ 1  4  9 16]
Element-wise square root: [1.         1.41421356 1.73205081 2.        ]

Element-wise comparison (a > 2): [False False  True  True]
Element-wise comparison (a == b): [False False False False]

Sum of a: 10
Mean of a: 2.5
Standard deviation of a: 1.118033988749895
Minimum of a: 1
Maximum of a: 4
Index of max value: 3


# Matrix Operations and Broadcasting

In [11]:
print("MATRIX MULTIPLICATION")

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.dot(A, B)
print(result)

MATRIX MULTIPLICATION
[[19 22]
 [43 50]]


In [18]:

mat=np.array([[1,2],[3,4]])
vec=np.array([10,20])
print("Matrix Multiplication with vectors : " , np.matmul(mat,vec))


print(f"\nMatrix A:")
print(f"Shape: {A.shape}")
print(f"Determinant: {np.linalg.det(A)}")
print(f"Transpose:\n{A.T}")
print(f"Inverse:\n{np.linalg.inv(A)}")

Matrix Multiplication with vectors :  [ 50 110]

Matrix A:
Shape: (2, 2)
Determinant: -2.0000000000000004
Transpose:
[[1 3]
 [2 4]]
Inverse:
[[-2.   1. ]
 [ 1.5 -0.5]]


## Broadcasting

In [19]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

vector = np.array([10, 20, 30])

broadcast_result = matrix + vector
print(broadcast_result)

[[11 22 33]
 [14 25 36]]


In [20]:
mat=np.array([[1,2],[3,4]])
print(mat+10)

[[11 12]
 [13 14]]


In [21]:
mat=np.array([[1,2,3],[4,5,6]])
row=np.array([10,20,30])
print(mat+row)

[[11 22 33]
 [14 25 36]]


In [23]:
a=np.array([1,2,3])
b=np.array([[10],[20],[30]])
print(a*b)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [24]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]


In [26]:
  print(" The End !!!!")

 The End !!!!
